// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go

package moduletesting

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/izumin5210/grapi/pkg/grapicmd/internal/module"
	reflect "reflect"
)

// MockGenerator is a mock of Generator interface
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return _m.recorder
}

// GenerateProject mocks base method
func (_m *MockGenerator) GenerateProject(rootDir string, useHead bool) error {
	ret := _m.ctrl.Call(_m, "GenerateProject", rootDir, useHead)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateProject indicates an expected call of GenerateProject
func (_mr *MockGeneratorMockRecorder) GenerateProject(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateProject", reflect.TypeOf((*MockGenerator)(nil).GenerateProject), arg0, arg1)
}

// GenerateService mocks base method
func (_m *MockGenerator) GenerateService(name string, cfg ServiceGenerationConfig) error {
	ret := _m.ctrl.Call(_m, "GenerateService", name, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateService indicates an expected call of GenerateService
func (_mr *MockGeneratorMockRecorder) GenerateService(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateService", reflect.TypeOf((*MockGenerator)(nil).GenerateService), arg0, arg1)
}

// ScaffoldService mocks base method
func (_m *MockGenerator) ScaffoldService(name string, cfg ServiceGenerationConfig) error {
	ret := _m.ctrl.Call(_m, "ScaffoldService", name, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScaffoldService indicates an expected call of ScaffoldService
func (_mr *MockGeneratorMockRecorder) ScaffoldService(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ScaffoldService", reflect.TypeOf((*MockGenerator)(nil).ScaffoldService), arg0, arg1)
}

// DestroyService mocks base method
func (_m *MockGenerator) DestroyService(name string) error {
	ret := _m.ctrl.Call(_m, "DestroyService", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyService indicates an expected call of DestroyService
func (_mr *MockGeneratorMockRecorder) DestroyService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DestroyService", reflect.TypeOf((*MockGenerator)(nil).DestroyService), arg0)
}

// GenerateCommand mocks base method
func (_m *MockGenerator) GenerateCommand(name string) error {
	ret := _m.ctrl.Call(_m, "GenerateCommand", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateCommand indicates an expected call of GenerateCommand
func (_mr *MockGeneratorMockRecorder) GenerateCommand(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateCommand", reflect.TypeOf((*MockGenerator)(nil).GenerateCommand), arg0)
}

// DestroyCommand mocks base method
func (_m *MockGenerator) DestroyCommand(name string) error {
	ret := _m.ctrl.Call(_m, "DestroyCommand", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyCommand indicates an expected call of DestroyCommand
func (_mr *MockGeneratorMockRecorder) DestroyCommand(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DestroyCommand", reflect.TypeOf((*MockGenerator)(nil).DestroyCommand), arg0)
}

// MockProjectGenerator is a mock of ProjectGenerator interface
type MockProjectGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockProjectGeneratorMockRecorder
}

// MockProjectGeneratorMockRecorder is the mock recorder for MockProjectGenerator
type MockProjectGeneratorMockRecorder struct {
	mock *MockProjectGenerator
}

// NewMockProjectGenerator creates a new mock instance
func NewMockProjectGenerator(ctrl *gomock.Controller) *MockProjectGenerator {
	mock := &MockProjectGenerator{ctrl: ctrl}
	mock.recorder = &MockProjectGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockProjectGenerator) EXPECT() *MockProjectGeneratorMockRecorder {
	return _m.recorder
}

// GenerateProject mocks base method
func (_m *MockProjectGenerator) GenerateProject(rootDir string, useHead bool) error {
	ret := _m.ctrl.Call(_m, "GenerateProject", rootDir, useHead)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateProject indicates an expected call of GenerateProject
func (_mr *MockProjectGeneratorMockRecorder) GenerateProject(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateProject", reflect.TypeOf((*MockProjectGenerator)(nil).GenerateProject), arg0, arg1)
}

// MockServiceGenerator is a mock of ServiceGenerator interface
type MockServiceGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockServiceGeneratorMockRecorder
}

// MockServiceGeneratorMockRecorder is the mock recorder for MockServiceGenerator
type MockServiceGeneratorMockRecorder struct {
	mock *MockServiceGenerator
}

// NewMockServiceGenerator creates a new mock instance
func NewMockServiceGenerator(ctrl *gomock.Controller) *MockServiceGenerator {
	mock := &MockServiceGenerator{ctrl: ctrl}
	mock.recorder = &MockServiceGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockServiceGenerator) EXPECT() *MockServiceGeneratorMockRecorder {
	return _m.recorder
}

// GenerateService mocks base method
func (_m *MockServiceGenerator) GenerateService(name string, cfg ServiceGenerationConfig) error {
	ret := _m.ctrl.Call(_m, "GenerateService", name, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateService indicates an expected call of GenerateService
func (_mr *MockServiceGeneratorMockRecorder) GenerateService(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateService", reflect.TypeOf((*MockServiceGenerator)(nil).GenerateService), arg0, arg1)
}

// ScaffoldService mocks base method
func (_m *MockServiceGenerator) ScaffoldService(name string, cfg ServiceGenerationConfig) error {
	ret := _m.ctrl.Call(_m, "ScaffoldService", name, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScaffoldService indicates an expected call of ScaffoldService
func (_mr *MockServiceGeneratorMockRecorder) ScaffoldService(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ScaffoldService", reflect.TypeOf((*MockServiceGenerator)(nil).ScaffoldService), arg0, arg1)
}

// DestroyService mocks base method
func (_m *MockServiceGenerator) DestroyService(name string) error {
	ret := _m.ctrl.Call(_m, "DestroyService", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyService indicates an expected call of DestroyService
func (_mr *MockServiceGeneratorMockRecorder) DestroyService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DestroyService", reflect.TypeOf((*MockServiceGenerator)(nil).DestroyService), arg0)
}

// MockCommandGenerator is a mock of CommandGenerator interface
type MockCommandGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockCommandGeneratorMockRecorder
}

// MockCommandGeneratorMockRecorder is the mock recorder for MockCommandGenerator
type MockCommandGeneratorMockRecorder struct {
	mock *MockCommandGenerator
}

// NewMockCommandGenerator creates a new mock instance
func NewMockCommandGenerator(ctrl *gomock.Controller) *MockCommandGenerator {
	mock := &MockCommandGenerator{ctrl: ctrl}
	mock.recorder = &MockCommandGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCommandGenerator) EXPECT() *MockCommandGeneratorMockRecorder {
	return _m.recorder
}

// GenerateCommand mocks base method
func (_m *MockCommandGenerator) GenerateCommand(name string) error {
	ret := _m.ctrl.Call(_m, "GenerateCommand", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateCommand indicates an expected call of GenerateCommand
func (_mr *MockCommandGeneratorMockRecorder) GenerateCommand(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateCommand", reflect.TypeOf((*MockCommandGenerator)(nil).GenerateCommand), arg0)
}

// DestroyCommand mocks base method
func (_m *MockCommandGenerator) DestroyCommand(name string) error {
	ret := _m.ctrl.Call(_m, "DestroyCommand", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyCommand indicates an expected call of DestroyCommand
func (_mr *MockCommandGeneratorMockRecorder) DestroyCommand(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DestroyCommand", reflect.TypeOf((*MockCommandGenerator)(nil).DestroyCommand), arg0)
}
