// Code generated by MockGen. DO NOT EDIT.
// Source: script.go

package moduletesting

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/izumin5210/grapi/pkg/grapicmd/internal/module"
	reflect "reflect"
)

// MockScript is a mock of Script interface
type MockScript struct {
	ctrl     *gomock.Controller
	recorder *MockScriptMockRecorder
}

// MockScriptMockRecorder is the mock recorder for MockScript
type MockScriptMockRecorder struct {
	mock *MockScript
}

// NewMockScript creates a new mock instance
func NewMockScript(ctrl *gomock.Controller) *MockScript {
	mock := &MockScript{ctrl: ctrl}
	mock.recorder = &MockScriptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockScript) EXPECT() *MockScriptMockRecorder {
	return _m.recorder
}

// Name mocks base method
func (_m *MockScript) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockScriptMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockScript)(nil).Name))
}

// Build mocks base method
func (_m *MockScript) Build(args ...string) error {
	_s := []interface{}{}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Build", _s...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build
func (_mr *MockScriptMockRecorder) Build(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Build", reflect.TypeOf((*MockScript)(nil).Build), arg0...)
}

// Run mocks base method
func (_m *MockScript) Run(args ...string) error {
	_s := []interface{}{}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Run", _s...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (_mr *MockScriptMockRecorder) Run(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockScript)(nil).Run), arg0...)
}

// MockScriptLoader is a mock of ScriptLoader interface
type MockScriptLoader struct {
	ctrl     *gomock.Controller
	recorder *MockScriptLoaderMockRecorder
}

// MockScriptLoaderMockRecorder is the mock recorder for MockScriptLoader
type MockScriptLoaderMockRecorder struct {
	mock *MockScriptLoader
}

// NewMockScriptLoader creates a new mock instance
func NewMockScriptLoader(ctrl *gomock.Controller) *MockScriptLoader {
	mock := &MockScriptLoader{ctrl: ctrl}
	mock.recorder = &MockScriptLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockScriptLoader) EXPECT() *MockScriptLoaderMockRecorder {
	return _m.recorder
}

// Load mocks base method
func (_m *MockScriptLoader) Load(dir string) error {
	ret := _m.ctrl.Call(_m, "Load", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load
func (_mr *MockScriptLoaderMockRecorder) Load(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Load", reflect.TypeOf((*MockScriptLoader)(nil).Load), arg0)
}

// Get mocks base method
func (_m *MockScriptLoader) Get(name string) (Script, bool) {
	ret := _m.ctrl.Call(_m, "Get", name)
	ret0, _ := ret[0].(Script)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (_mr *MockScriptLoaderMockRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Get", reflect.TypeOf((*MockScriptLoader)(nil).Get), arg0)
}

// Names mocks base method
func (_m *MockScriptLoader) Names() []string {
	ret := _m.ctrl.Call(_m, "Names")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Names indicates an expected call of Names
func (_mr *MockScriptLoaderMockRecorder) Names() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Names", reflect.TypeOf((*MockScriptLoader)(nil).Names))
}
