// Code generated by MockGen. DO NOT EDIT.
// Source: ui.go

// Package moduletesting is a generated GoMock package.
package moduletesting

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUI is a mock of UI interface
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *MockUIMockRecorder
}

// MockUIMockRecorder is the mock recorder for MockUI
type MockUIMockRecorder struct {
	mock *MockUI
}

// NewMockUI creates a new mock instance
func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &MockUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUI) EXPECT() *MockUIMockRecorder {
	return m.recorder
}

// Output mocks base method
func (m *MockUI) Output(msg string) {
	m.ctrl.Call(m, "Output", msg)
}

// Output indicates an expected call of Output
func (mr *MockUIMockRecorder) Output(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockUI)(nil).Output), msg)
}

// Section mocks base method
func (m *MockUI) Section(msg string) {
	m.ctrl.Call(m, "Section", msg)
}

// Section indicates an expected call of Section
func (mr *MockUIMockRecorder) Section(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Section", reflect.TypeOf((*MockUI)(nil).Section), msg)
}

// Subsection mocks base method
func (m *MockUI) Subsection(msg string) {
	m.ctrl.Call(m, "Subsection", msg)
}

// Subsection indicates an expected call of Subsection
func (mr *MockUIMockRecorder) Subsection(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subsection", reflect.TypeOf((*MockUI)(nil).Subsection), msg)
}

// Warn mocks base method
func (m *MockUI) Warn(msg string) {
	m.ctrl.Call(m, "Warn", msg)
}

// Warn indicates an expected call of Warn
func (mr *MockUIMockRecorder) Warn(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockUI)(nil).Warn), msg)
}

// Error mocks base method
func (m *MockUI) Error(msg string) {
	m.ctrl.Call(m, "Error", msg)
}

// Error indicates an expected call of Error
func (mr *MockUIMockRecorder) Error(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockUI)(nil).Error), msg)
}

// ItemSuccess mocks base method
func (m *MockUI) ItemSuccess(msg string) {
	m.ctrl.Call(m, "ItemSuccess", msg)
}

// ItemSuccess indicates an expected call of ItemSuccess
func (mr *MockUIMockRecorder) ItemSuccess(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemSuccess", reflect.TypeOf((*MockUI)(nil).ItemSuccess), msg)
}

// ItemSkipped mocks base method
func (m *MockUI) ItemSkipped(msg string) {
	m.ctrl.Call(m, "ItemSkipped", msg)
}

// ItemSkipped indicates an expected call of ItemSkipped
func (mr *MockUIMockRecorder) ItemSkipped(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemSkipped", reflect.TypeOf((*MockUI)(nil).ItemSkipped), msg)
}

// ItemFailure mocks base method
func (m *MockUI) ItemFailure(msg string) {
	m.ctrl.Call(m, "ItemFailure", msg)
}

// ItemFailure indicates an expected call of ItemFailure
func (mr *MockUIMockRecorder) ItemFailure(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemFailure", reflect.TypeOf((*MockUI)(nil).ItemFailure), msg)
}

// Confirm mocks base method
func (m *MockUI) Confirm(msg string) (bool, error) {
	ret := m.ctrl.Call(m, "Confirm", msg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm
func (mr *MockUIMockRecorder) Confirm(msg interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockUI)(nil).Confirm), msg)
}
