// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/golang/mock/mockgen"
	_ "github.com/izumin5210/gex/cmd/gex"
	_ "github.com/jessevdk/go-assets-builder"
	_ "github.com/mitchellh/gox"
)
