// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gencmd

import (
	"github.com/izumin5210/grapi/pkg/cli"
	"github.com/izumin5210/grapi/pkg/grapicmd"
	"github.com/rakyll/statik/fs"
)

// Injectors from wire.go:

func newApp(command *Command) (*App, error) {
	ctx := ProvideCtx(command)
	grapicmdCtx := ProvideGrapiCtx(ctx)
	aferoFs := grapicmd.ProvideFS(grapicmdCtx)
	io := grapicmd.ProvideIO(grapicmdCtx)
	ui := cli.UIInstance(io)
	rootDir := grapicmd.ProvideRootDir(grapicmdCtx)
	fileSystem, err := fs.New()
	if err != nil {
		return nil, err
	}
	shouldRunFunc := ProvideShouldRun(command)
	generator := NewGenerator(aferoFs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
