// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gencmd

import (
	"github.com/izumin5210/grapi/pkg/cli"
	"github.com/izumin5210/grapi/pkg/grapicmd"
)

// Injectors from wire.go:

func newApp(command *Command) (*App, error) {
	ctx := ProvideCtx(command)
	grapicmdCtx := ProvideGrapiCtx(ctx)
	fs := grapicmd.ProvideFS(grapicmdCtx)
	io := grapicmd.ProvideIO(grapicmdCtx)
	ui := cli.UIInstance(io)
	rootDir := grapicmd.ProvideRootDir(grapicmdCtx)
	fileSystem := ProvideTemplateFS(command)
	shouldRunFunc := ProvideShouldRun(command)
	generator := NewGenerator(fs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
