#!/usr/bin/env bash

set -e
set -o pipefail

BIN_DIR=$HOME/bin

section() {
  printf "\e[34m--> $1\e[0m\n"
}

install_protoc() {
  section "Installing protoc"

  if [ ! -d "${BIN_DIR}/protoc" ]; then
    curl -L -s https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip -o protoc-$PROTOBUF_VERSION.zip
    unzip -o protoc-$PROTOBUF_VERSION.zip -d $HOME
  else
    echo "skipped"
  fi

  protoc  --version
}

main() {
  install_protoc
}

main
