#!/usr/bin/env bash

set -e
set -o pipefail

go get -u github.com/golang/lint/golint
make lint

if [ "$COVERAGE_ENABLED" = 1 ]; then
  make cover
  bash <(curl -s https://codecov.io/bash)
else
  make test
fi
