// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/izumin5210/grapi/pkg/clui"
	"github.com/izumin5210/grapi/pkg/command"
	"github.com/izumin5210/grapi/pkg/grapicmd"
	"github.com/izumin5210/grapi/pkg/grapicmd/internal/module"
	"github.com/izumin5210/grapi/pkg/grapicmd/internal/usecase"
	"github.com/izumin5210/grapi/pkg/protoc"
)

// Injectors from wire.go:

func NewUI(ctx *grapicmd.Ctx) clui.UI {
	cluiUI := ProvideUI(ctx)
	return cluiUI
}

func NewCommandExecutor(ctx *grapicmd.Ctx) command.Executor {
	cluiUI := ProvideUI(ctx)
	executor := ProvideCommandExecutor(ctx, cluiUI)
	return executor
}

func NewGenerator(ctx *grapicmd.Ctx) module.Generator {
	cluiUI := ProvideUI(ctx)
	generator := ProvideGenerator(ctx, cluiUI)
	return generator
}

func NewScriptLoader(ctx *grapicmd.Ctx) module.ScriptLoader {
	cluiUI := ProvideUI(ctx)
	executor := ProvideCommandExecutor(ctx, cluiUI)
	scriptLoader := ProvideScriptLoader(ctx, executor)
	return scriptLoader
}

func NewProtocWrapper(ctx *grapicmd.Ctx) (protoc.Wrapper, error) {
	cluiUI := ProvideUI(ctx)
	config := ProvideGexConfig(ctx)
	repository, err := ProvideToolRepository(ctx, config)
	if err != nil {
		return nil, err
	}
	wrapper := ProvideProtocWrapper(ctx, cluiUI, repository)
	return wrapper, nil
}

func NewInitializeProjectUsecase(ctx *grapicmd.Ctx) usecase.InitializeProjectUsecase {
	config := ProvideGexConfig(ctx)
	cluiUI := ProvideUI(ctx)
	generator := ProvideGenerator(ctx, cluiUI)
	initializeProjectUsecase := ProvideInitializeProjectUsecase(ctx, config, cluiUI, generator)
	return initializeProjectUsecase
}
