// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package testing

import (
	"github.com/izumin5210/grapi/pkg/cli"
	"github.com/izumin5210/grapi/pkg/gencmd"
	"github.com/izumin5210/grapi/pkg/grapicmd"
)

// Injectors from wire.go:

func NewTestApp(ctx *gencmd.Ctx, command *gencmd.Command, ui cli.UI) (*gencmd.App, error) {
	grapicmdCtx := gencmd.ProvideGrapiCtx(ctx)
	fs := grapicmd.ProvideFS(grapicmdCtx)
	rootDir := grapicmd.ProvideRootDir(grapicmdCtx)
	fileSystem := gencmd.ProvideTemplateFS(command)
	shouldRunFunc := gencmd.ProvideShouldRun(command)
	generator := gencmd.NewGenerator(fs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &gencmd.App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
