// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package testing

import (
	"github.com/izumin5210/grapi/pkg/cli"
	"github.com/izumin5210/grapi/pkg/gencmd"
	"github.com/izumin5210/grapi/pkg/grapicmd"
	"github.com/rakyll/statik/fs"
)

// Injectors from wire.go:

func NewTestApp(command *gencmd.Command, ui cli.UI) (*gencmd.App, error) {
	ctx := gencmd.ProvideCtx(command)
	grapicmdCtx := gencmd.ProvideGrapiCtx(ctx)
	aferoFs := grapicmd.ProvideFS(grapicmdCtx)
	rootDir := grapicmd.ProvideRootDir(grapicmdCtx)
	path := gencmd.ProvidePath(rootDir)
	fileSystem, err := fs.New()
	if err != nil {
		return nil, err
	}
	shouldRunFunc := gencmd.ProvideShouldRun(command)
	generator := gencmd.NewGenerator(aferoFs, ui, path, fileSystem, shouldRunFunc)
	app := &gencmd.App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
